### ISSUE TITLE
TypeError: e.getIn is not a function

### ISSUE THREAD

**Issue by LuigiClaudio** [hupe1980/gatsby-theme-netlify-cms#2]
I've added this theme to the gatsby-starter-default starter. When hitting http://localhost:8000/admin/#/ it returns  this: 
```
Error loading the CMS configuration
Config Errors:
TypeError: e.getIn is not a function
```
In console I see:
```
Uncaught (in promise) TypeError: e.getIn is not a function
in webpack:///./node_modules/netlify-cms-backend-fs/dist/index.js
```

Any suggestion on what to look out for?

**Comment by cedricdelpoux** [comment]
The same error happened to me

**Comment by LuigiClaudio** [comment]
@cedricdelpoux I'm using `netlify-cms-proxy-server` - you can read more here https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
